version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=pgsql"
      - "XDG_CONFIG_HOME=/app"
    ports:
      - "80:80"
    networks:
      - lumen_network
    depends_on:
      - lumen

  lumen:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    container_name: lumen
    volumes:
      - ../project:/var/www
    environment:
      - "COMPOSER_MEMORY_LIMIT=-1"
    networks:
      - lumen_network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: lumen_db
    restart: always
    environment:
      POSTGRES_DB: sputnik
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - lumen_network

networks:
  lumen_network:

volumes:
  postgres_data:
